### ISSUE TITLE
Post header links not working

### ISSUE THREAD

**Issue by zackgemmell** [zackgemmell/portfolio-2020#1]
**Steps to reproduce** 

1. Navigate to a post
2. Click on Work or About in the navigation bar

![Screen Shot 2020-11-18 at 7 46 46 PM](https://user-images.githubusercontent.com/6632499/99618785-e82dfc00-29d6-11eb-9871-b6fb9353ba37.png)

**Expected result**

The browser should navigate to either zackgemmell.com/#projects or zackgemmell.com/#about

**Comment by zackgemmell** [comment]
![Screen Shot 2020-11-19 at 9 54 18 AM](https://user-images.githubusercontent.com/6632499/99704421-3978d280-2a4d-11eb-854c-ef1aa74ccf45.png)

It looks like the problem lies somewhere in `js/script.js`

**Comment by Rubon72** [comment]
done, plz check
